name = "resume"
main = "worker.js"
compatibility_date = "2024-07-17"

[site]
bucket = "./build"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "ppei.dev/*"
zone_name = "ppei.dev"

[[routes]]
pattern = "www.ppei.dev/*"
zone_name = "ppei.dev" 